version: "3.8"
services:

  server:
    build: 
      context: .
      dockerfile: ./src/Dockerfile
    volumes:
      - ./server:/app
    ports:
     - 3001:3000
    depends_on:
      - db
      - mongo
    restart: unless-stopped
    environment:       
      - HOST=0.0.0.0
      - DATABASE_DATABASE=celabs
      - DATABASE_USER=admin
      - DATABASE_PASSWORD=1234
      - DATABASE_HOST=db
      - DATABASE_PORT=3306
      - MONGO_HOST=mongo
      - MONGO_DB=celabs

  db:
    image: mysql:10
    environment: 
      - MYSQL_DATABASE=celabs
      - MYSQL_ROOT_PASSWORD=secret-password
      - MYSQL_USER=root
      - MYSQL_PASSWORD=1234
    ports: 
      - 3002:3306

  mongo:
    image: mongo
    restart: unless-stopped
    environment:
      MONGO_INITDB_ROOT_USERNAME: root
      MONGO_INITDB_ROOT_PASSWORD: example
    ports:
      - 3003:27017

  mongo-express:
    image: mongo-express
    restart: unless-stopped
    depends_on:
      - mongo
    ports:
      - 3004:8081
    environment:
      ME_CONFIG_MONGODB_ADMINUSERNAME: root
      ME_CONFIG_MONGODB_ADMINPASSWORD: example